apps/accounts/urls.py
from apps.accounts.forms import EmailAuthenticationForm
from django.conf.urls import url

from django.utils.translation import ugettext_lazy as _

from .views import *


urlpatterns = [
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
        'template_name': 'accounts/login.html',
        'extra_context': {'title': _('Login')},
        'authentication_form': EmailAuthenticationForm
        },
        name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^singup/$', singup, name='singup'),

    url(r'^password_change/$',
        'django.contrib.auth.views.password_change',
        {
            'template_name': 'accounts/password_change.html',
            'extra_context': {'title': _('Change password')}
        },
        name='password_change'
    ),
    url(r'^password_change/done/$',
        'django.contrib.auth.views.password_change_done',
        {
            'template_name': 'accounts/password_change_done.html',
            'extra_context': {'title': _('Change password')}
        },
        name='password_change_done'
    ),
    url(r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        {'template_name': 'accounts/password_reset.html'},
        name='password_reset'
    ),
    url(r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'accounts/password_reset_done.html'},
        name='password_reset_done'
    ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'accounts/password_reset_confirm.html'},
        name='password_reset_confirm'
    ),
    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'accounts/password_reset_complete.html'},
        name='password_reset_complete'
    )
]

apps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',

    url(r'^', include('apps.accounts.urls')),
	# Admin
	url(r'^admin/', include(admin.site.urls)),

	# Home
	url(r'^$', 'apps.views.home', name='home'),
	url(r'^results/$', 'apps.views.todos', name='todos'),
	url(r'^(?P<id>\d+)/$', 'apps.views.del_todo', name='del_todo'),
	url(r'^done/(?P<id>\d+)/$', 'apps.views.done_todo', name='done_todo'),

	url(r'^diesel-up/', include('apps.diesel.urls')),

	url(r'^chat/', include('apps.chat.urls')),

	url(r'^finance/', include('apps.finance.urls')),
)


# For serve static, media, templates in develop mode
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

apps/accounts/models.py
# -*- coding: utf-8 -*-
from decimal import Decimal
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager



AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = True
AbstractUser._meta.get_field('first_name').blank = True
AbstractUser._meta.get_field('last_name').blank = True


class User(AbstractUser):
    phone = models.CharField(verbose_name=u'Телефон', max_length=256, validators=[MinLengthValidator(4)])

apps/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.utils.translation import ugettext as _

from .models import User


class EmailAuthenticationForm(AuthenticationForm):
	username = forms.CharField(label=_('Login or E-Mail'))


class SingUpForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'required'}, render_value=False),
								label=_('Password'))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'required'}, render_value=False),
								label=_('Password (again)'))

	def clean_username(self):
		if User.objects.filter(username__iexact=self.cleaned_data['username']):
			raise forms.ValidationError(_("This username is already in use. Please supply a different username."))
		return self.cleaned_data['username']

	def clean_email(self):
		if User.objects.filter(email__iexact=self.cleaned_data['email']):
			raise forms.ValidationError(
				_("This email address is already in use. Please supply a different email address."))
		return self.cleaned_data['email']

	def clean(self):
		if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
			if self.cleaned_data['password1'] != self.cleaned_data['password2']:
				raise forms.ValidationError(_('Passwords do not match!'))
		return self.cleaned_data

	def save(self, commit=True):
		user = super(SingUpForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

	class Meta:
		model = User
		exclude = ['last_login', 'is_staff', 'is_active', 'date_joined', 'password',
				   'user_permissions', 'is_superuser', 'groups', 'raw_password']

apps/accounts/views.py
# -*- coding: utf-8 -*-
from decimal import Decimal
import user

from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import SingUpForm


@csrf_exempt
def singup(request):
	context = {}
	context['form'] = SingUpForm(request.POST or None)

	if request.POST and context['form'].is_valid():
		new_user = context['form'].save()
		context['new_user'] = new_user
		new_user.backend = 'apps.accounts.auth.EmailOrUsernameModelBackend'
		login(request, new_user)
		return redirect('/', username=new_user.username)
	return render(request, 'accounts/singup.html', context)

apps/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1 class="text-center title_form">{% trans 'Change your password' %}</h1>
{% if ok == True %}
	<h3 class="text-center">{% trans 'Password successfully received' %}</h3>
{% else %}

<form method="post" action="/change_password/" class="form-horizontal">
	{% csrf_token %}
	{{ form.management_form }}
	{% if form.non_field_errors %}
		<div class="col-sm-12">
			<div class="alert alert-danger all col-sm-6 col-sm-offset-3">
					{{ form.non_field_errors }}
			</div>
		</div>
	{% endif %}

	{% for field in form %}
		<div class="form-group {% if field.errors %}has-error{% endif %} col-sm-12">
			<div class="col-sm-3 col-sm-offset-3">
				<label for='id_username' class='control-label label_field'>
					{{ field.label }}
				</label>
				{% if field.errors %}
					<span class="errors_field control-label">{{ field.errors }}</span>
				{% else %}
					<span class="help-text">{{ field.help_text }}</span>
				{% endif %}
			</div>
			<div class="col-sm-3">
				{{ field }}
			</div>
		</div>
	{% endfor %}
	<div class="form-group col-sm-12">
		<div class="text-center col-sm-offset-6 col-sm-3">
			<button type="submit" value="Send" class="btn btn-primary b-form_submit col-md-12">{% trans 'Change your password' %}</button>
		</div>
	</div>
</form>
{% endif %}

<script>
	$( "input" ).addClass( "form-control" );
	$( "select" ).addClass( "form-control" );
	$( "option" ).addClass( "form-control" );
</script>


{% endblock %}

apps/accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="b-wrapper m-app_accounts m-template_singup">
	<h1 class="text-center title_form">Редактировать профиль</h1>

    <form method="post" action="" class="form-horizontal form">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group first_name">
            <label for="id_first_name">Имя</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.first_name.name }}" class="form-control" id="id_first_name" value="{{ form.first_name.value }}">
            </div>
        </div>
        <div class="form-group last_name">
            <label for="id_last_name">Фамилия</label>
            <div class="input-group last_name">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.last_name.name }}" class="form-control" id="id_last_name" value="{{ form.last_name.value }}">
            </div>
        </div>
        <div class="form-group email">
            <label for="id_email">Электронная почта</label>
            <div class="input-group email">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <input type="email" name="{{ form.email.name }}" required="" class="form-control" id="id_email" value="{{ form.email.value }}">
            </div>
        </div>
        <div class="form-group sity">
            <label for="id_sity">Адрес</label>
            <div class="input-group sity">
                <div class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></div>
                <input type="text" name="{{ form.address.name }}" class="form-control" id="id_sity" value="{{ form.address.value }}">
            </div>
        </div>
        <div class="form-group phone">
            <label for="id_phone">Телефон</label>
            <div class="input-group phone">
                <div class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></div>
                <input type="text" name="{{ form.phone.name }}" required="" class="form-control" id="id_phone" value="{{ form.phone.value }}">
            </div>
        </div>
		<button type="submit" class="b-singup_btn">Отредактировать</button>
	</form>
    <div>
{% endblock %}

apps/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="b-wrapper m-app_accounts m-template_singup">
	<h1 class="text-center title_form">Войти</h1>
    <form method="post" action="/login/" class="form-horizontal form login_form">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_name">Логин или e-mail</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.username.name }}" required="" class="form-control" id="id_username">
            </div>
        </div>
        <div class="form-group">
            <label for="id_name">Пароль</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <input type="password" name="{{ form.password.name }}" required="" class="form-control" id="id_password">
            </div>
        </div>
        <div>
            <button type="submit">Войти</button>
        </div>
	</form>

<div>
{% endblock %}

apps/accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1 class="text-center title_form">Сменить пароль</h1>
{% if ok == True %}
	<h3 class="text-center">Ваш пароль изменен</h3>
    <a href="/">перейти на главную</a>
    <a href="{% url 'profile' %}">перейти в профиль</a>
{% else %}

<form method="post" action="" class="form-horizontal">
	{% csrf_token %}
	{{ form.management_form }}
	{% if form.non_field_errors %}
		<div class="col-sm-12">
			<div class="alert alert-danger all col-sm-6 col-sm-offset-3">
					{{ form.non_field_errors }}
			</div>
		</div>
	{% endif %}

	{% for field in form %}
		<div class="form-group {% if field.errors %}has-error{% endif %} col-sm-12">
			<div class="col-sm-3 col-sm-offset-3">
				<label for='id_username' class='control-label label_field'>
					{{ field.label }}
				</label>
				{% if field.errors %}
					<span class="errors_field control-label">{{ field.errors }}</span>
				{% else %}
					<span class="help-text">{{ field.help_text }}</span>
				{% endif %}
			</div>
			<div class="col-sm-3">
				{{ field }}
			</div>
		</div>
	{% endfor %}
	<div class="form-group col-sm-12">
		<div class="text-center col-sm-offset-6 col-sm-3">
			<button type="submit" value="Send" class="btn btn-primary b-form_submit col-md-12">Сменить пароль</button>
		</div>
	</div>
</form>
{% endif %}

<script>
	$( "input" ).addClass( "form-control" );
	$( "select" ).addClass( "form-control" );
	$( "option" ).addClass( "form-control" );
</script>


{% endblock %}

apps/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block content %}

	<h1>Пароль изменён!</h1>

{% endblock %}

apps/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1 class="text-center title_form">{{ title }}</h1>
<p  class="b-password_reset__title text-center">{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
<form method="post" action="" class="form-horizontal">
	{% csrf_token %}
	{{ form.management_form }}
	{% if form.non_field_errors %}
		<div class="col-sm-12">
			<div class="alert alert-danger all col-sm-6 col-sm-offset-3">
					{{ form.non_field_errors }}
			</div>
		</div>
	{% endif %}

	{% for field in form %}
		<div class="form-group {% if field.errors %}has-error{% endif %} col-sm-12">
			<div class="col-sm-3 col-sm-offset-3">
				<label for='id_username' class='control-label label_field'>
					{{ field.label }}
				</label>
				{% if field.errors %}
					<span class="errors_field control-label">{{ field.errors }}</span>
				{% else %}
					<span class="help-text">{{ field.help_text }}</span>
				{% endif %}
			</div>
			<div class="col-sm-3">
				{{ field }}
			</div>
		</div>
	{% endfor %}
	<div class="form-group col-sm-12">
		<div class="text-center col-sm-offset-6 col-sm-3">
			<button type="submit" value="Send" class="btn btn-primary b-form_submit col-md-12">{% trans 'Reset my password' %}</button>
		</div>
	</div>
</form>

<script>
	$( "input" ).addClass( "form-control" );
</script>


{% endblock %}

apps/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1>{{ title }}</h1>

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

apps/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1>{{ title }}</h1>

{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

apps/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

	<h1>{{ title }}</h1>

	<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

	<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

apps/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-12 m-template_profile">
	<div class="b-wrapper">
	<h1 class="text-center">Профиль</h1>
		<div class="col-md-4">
			<ul class="list-group">
				<li class="list-group-item">{{ user.last_name }} {{ user.first_name }} ( {{ user }} )</li>
                {% if user.balance %}
                    <li class="list-group-item">Счет: {{ user.balance }} сом</li>
                {% else %}
                    <li class="list-group-item">Счет: 0 сом</li>
                {% endif %}
				<li class="list-group-item"><a href="{% url 'edit_profile' %}">Редактировать профиль</a></li>
				<li class="list-group-item"><a href="{% url 'password_change' %}">Изменить пароль</a></li>
                {% for company in companies %}
				    <li class="list-group-item">
                        <p>{{ company.name }}</p>
                        <p>{{ company.manager }}</p>
                        <p>{{ company.address }}</p>
                        <p>{{ company.phone }}</p>
                        <p>{{ company.email }}</p>
                        <p>{{ company.website }}</p>
                        <a href="{% url 'update_company' company.id %}">Редактировать компанию</a>
                    </li>
                {% endfor %}
                {% if user.company == True %}
                    {% if user.companies.count == 0 %}
                        <li class="list-group-item"><a href="{% url 'create_company' %}">Создать компанию</a></li>
                    {% endif %}
                {% endif %}
			</ul>
		</div>
		<div class="col-md-8">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active">
					<a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">tab1</a>
				</li>
				<li role="presentation">
					<a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">tab2</a>
				</li>
				<li role="presentation">
					<a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">tab3</a>
				</li>
				<li role="presentation">
					<a href="#tab4" aria-controls="tab4" role="tab" data-toggle="tab">tab4</a>
				</li>
			</ul>
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="tab1">
					<table class="table">
						<thead>
							<tr>
								<th>Заголовок1</th>
								<th>Заголовок2</th>
								<th>Заголовок3</th>
								<th>Заголовок4</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="tab2">
					<table class="table">
						<thead>
							<tr>
								<th>Заголовок1</th>
								<th>Заголовок2</th>
								<th>Заголовок3</th>
								<th>Заголовок4</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="tab3">
					<table class="table">
						<thead>
							<tr>
								<th>Заголовок1</th>
								<th>Заголовок2</th>
								<th>Заголовок3</th>
								<th>Заголовок4</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="tab4">
					<table class="table">
						<thead>
							<tr>
								<th>Заголовок1</th>
								<th>Заголовок2</th>
								<th>Заголовок3</th>
								<th>Заголовок4</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
							<tr>
								<td>Поле1</td>
								<td>Поле2</td>
								<td>Поле3</td>
								<td>Поле4</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>



















{% comment %}
{% if user.company == True %}
    {% if user.companies.count == 0 %}
        <a href="{% url 'create_company' %}">Создать компанию</a>
    {% endif %}
{% endif %}
    <div class="col-md-12">
        <h1>Настройки юзера</h1>
        <p>{{ user }}</p>
        <p>{{ user.first_name }}</p>
        <p>{{ user.last_name }}</p>
        <p>{{ user.balance }}</p>
        <p>{{ user.email }}</p>
        <p>{{ user.phone }}</p>
        <p>г. {{ user.sity }}, ул. {{ user.street }}, д. {{ user.home }}</p>
        <a href="{% url 'edit_profile' user.id %}">Редактировать</a>
    </div>
    <div class="col-md-12">
        <h1>Компания</h1>
        {% for company in companies %}
            <p>{{ company.name }}</p>
            <p>{{ company.address }}</p>
            <p>{{ company.phone }}</p>
            <p>{{ company.email }}</p>
            <p>{{ company.website }}</p>
            <a href="">Редактировать</a>
        {% endfor %}
    </div>

    <div class="col-md-12">
        <h1>Участие в лотах</h1>
        {% for price in prices %}
            <p>{{ price.lot }}</p>
            <a href="{% url 'lot_item' price.lot.category.slug price.lot.slug %}">Ссылка на лот</a>
            <a href="">Удалить</a>
        {% endfor %}
    </div>

    <div class="col-md-12">
        <h1>Купоны</h1>
        {% for ticket in tickets %}
            <p>{{ ticket.date|date:'d.m.Y H:m' }}</p>
            <p>{{ ticket.lot }}</p>
            <p>{{ ticket.price }}</p>
            {% if ticket.file %}
                <a href="{{ ticket.file.url }}">Скачать</a>
            {% endif %}
        {% endfor %}
    </div>
{% endcomment %}
{% endblock %}

apps/accounts/templates/accounts/singup.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="b-wrapper m-app_accounts m-template_singup">
	<h1 class="text-center title_form">Регистрация</h1>
    <div class="signup_btn_reg">
        <button class="client">Пройти регистрацию как клиент</button>
        <button class="company">Пройти регистрацию как компания</button>
    </div>
    <form method="post" action="/singup/" class="form-horizontal form">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_username">Логин</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.username.name }}" required="" class="form-control" id="id_username">
            </div>
        </div>
        <div class="form-group first_name">
            <label for="id_first_name">Имя</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.first_name.name }}" class="form-control" id="id_first_name">
            </div>
        </div>
        <div class="form-group last_name">
            <label for="id_last_name">Фамилия</label>
            <div class="input-group last_name">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <input type="text" name="{{ form.last_name.name }}" class="form-control" id="id_last_name">
            </div>
        </div>
        <div class="form-group email">
            <label for="id_email">Электронная почта</label>
            <div class="input-group email">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <input type="email" name="{{ form.email.name }}" required="" class="form-control" id="id_email">
            </div>
        </div>
        <div class="form-group company_name">
            <label for="id_company_name">Название компании</label>
            <div class="input-group company_name">
                <div class="input-group-addon"><span class="glyphicon glyphicon-briefcase"></span></div>
                <input type="text" name="{{ form.company_name.name }}" class="form-control" id="id_company_name">
            </div>
        </div>
        <div class="form-group sity">
            <label for="id_sity">Адрес</label>
            <div class="input-group sity">
                <div class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></div>
                <input type="text" name="{{ form.address.name }}" class="form-control" id="id_sity">
            </div>
        </div>
        <div class="form-group phone">
            <label for="id_phone">Телефон</label>
            <div class="input-group phone">
                <div class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></div>
                <input type="text" name="{{ form.phone.name }}" required="" class="form-control" id="id_phone">
            </div>
        </div>
        <div class="company_form form-group">
            <input type="radio" id="id_company" name="{{ form.company.name }}">
        </div>
        <div class="client_form form-group">
            <input type="radio" id="id_client" name="{{ form.client.name }}">
        </div>
        <div class="form-group">
            <label for="id_password1">Пароль</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <input type="password" name="{{ form.password1.name }}" required="" class="form-control" id="id_password1">
            </div>
        </div>
        <div class="form-group">
            <label for="id_password2">Пароль (еще раз)</label>
            <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <input type="password" name="{{ form.password2.name }}" required="" class="form-control" id="id_password2">
            </div>
        </div>
		<button type="submit" class="b-singup_btn">Зарегистрироваться</button>
	</form>
<div>

<script>
    $('.form').hide()
    $('.client_form').hide()
    $('.company_form').hide()
    $('.client').on('click', function(){
        $('#id_client').prop('checked', true);
        $('#id_company').prop('checked', false);
        $('.form').show()
        $('.company_name').hide()
        $('.sity').hide()
    });
    $('.company').on('click', function(){
        $('#id_company').prop('checked', true);
        $('#id_client').prop('checked', false);
        $('.form').show()
        $('.first_name').show()
        $('.last_name').show()
        $('.company_name').show()
        $('.sity').show()
    });
</script>
{% endblock %}