apps/diesel/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^$', views.topics, name='diesel_up_topics'),

	url(r'^up/(?P<id>\d+)/$', views.up_force, name='diesel_up_force'),

	# url(r'^time/$', views.up_time, name='diesel_up_time'),

	url(r'^add/$', views.add, name='diesel_up_add'),
	url(r'^edit/(?P<id>\d+)/$', views.edit, name='diesel_up_edit'),
	url(r'^deleted/(?P<id>\d+)/$', views.deleted, name='topic_deleted'),
]

apps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',

    url(r'^', include('apps.accounts.urls')),
	# Admin
	url(r'^admin/', include(admin.site.urls)),

	# Home
	url(r'^$', 'apps.views.home', name='home'),
	url(r'^results/$', 'apps.views.todos', name='todos'),
	url(r'^(?P<id>\d+)/$', 'apps.views.del_todo', name='del_todo'),
	url(r'^done/(?P<id>\d+)/$', 'apps.views.done_todo', name='done_todo'),

	url(r'^diesel-up/', include('apps.diesel.urls')),

	url(r'^chat/', include('apps.chat.urls')),

	url(r'^finance/', include('apps.finance.urls')),
)


# For serve static, media, templates in develop mode
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

apps/diesel/models.py
# coding: utf-8
from time import sleep
import re
from apps import settings
from grab import Grab
from django.db import models


class Log(models.Model):
	topic = models.ForeignKey('Topic', verbose_name=u'Топик')
	views = models.PositiveIntegerField(verbose_name=u'Счетчик')
	views_diff = models.PositiveIntegerField(verbose_name=u'Разница')
	datetime = models.DateTimeField(verbose_name=u'Дата и время', auto_now=True)

	class Meta:
		ordering = ['-datetime']
		verbose_name = u'Записи'
		verbose_name_plural = u'Записи'


class Topic(models.Model):
	login = models.CharField(verbose_name=u'Логин', max_length=128, help_text=u'на diesel.elcat.kg')
	password = models.CharField(verbose_name=u'Пароль', max_length=128, help_text=u'на diesel.elcat.kg')
	user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='User', default= 0)
	url = models.URLField(verbose_name=u'URl')
	title = models.CharField(verbose_name=u'Заголовок', max_length=256)
	text = models.TextField(verbose_name=u'Текст')
	count = models.PositiveIntegerField(verbose_name=u'Число апов', default=0, blank=True, editable=False)
	views = models.PositiveIntegerField(verbose_name=u'Просмотры', null=True, blank=True)

	repeat = models.TimeField(verbose_name=u'Время', default='1:00:00', null=True, blank=True)
	last_up = models.DateTimeField(verbose_name=u'Последний ап', auto_now=True)
	created_at = models.DateTimeField(verbose_name=u'Создано', auto_now_add=True)
	deleted = models.BooleanField(verbose_name=u'Удалить', default=False)
	public = models.BooleanField(verbose_name=u'Опубликовать', default=True)

	message_title = models.CharField(verbose_name=u'заголвоок сообщения', max_length=500)

	def __unicode__(self):
		return self.title

	def up(self):
		try:
			g = Grab()

			# Вход
			data = {
				'UserName': self.login.encode('cp1251'),
				'PassWord': self.password.encode('cp1251')
			}
			g.setup(
				post=data,
				connect_timeout=30,
				timeout=60
			)
			g.go(url='http://diesel.elcat.kg/index.php?act=Login&CODE=01&CookieDate=1')

			# Переходим в тему
			g.setup(post=None)
			g.go(url=self.url + '&st=40')

			# Находим старые апы
			html = g.response.body

			# Удаляем старые апы
			del_regex = "up&#33;[\s\S]*?javascript:delete_post\('(.+?)'\)"
			compiled_del_regex = re.compile(del_regex)
			links_to_del = compiled_del_regex.findall(html)

			# обход в цикле по ссылкам, тема удал.
			for link in links_to_del:
				link = link.replace('&amp;', '&')
				g.go(url=link)
				sleep(10)
			g.go(url=self.url)

			# Апаем тему
			f = g.doc.rex_text('<input type="hidden" name="f" value="([\d]+)" />')
			t = g.doc.rex_text('<input type="hidden" name="t" value="([\d]+)" />')
			auth_key = g.doc.rex_text('<input type="hidden" name="auth_key" value="([\w]+)" />')

			data = {
				'act': 'Post',
				'CODE': '03',
				'f': f,
				't': t,
				'st': '0',
				'auth_key': auth_key,
				'fast_reply_used': '1',
				'Post': 'up!',
				'enabletrack': '1',
				'enableemo': '1',
				'enablesig': '1',
			}

			g.setup(post=data)
			g.go(url='http://diesel.elcat.kg/index.php?')

			# Title
			self.title = g.doc.rex_text('<title>(.*) - Diesel Forum</title>')

			# Views
			g.go('http://diesel.elcat.kg/index.php?showforum=' + f)
			self.views = int(g.doc.rex_text('<!-- Begin Topic Entry ' + t + ' -->[\s\S]*?<td align="center" class="row2">([\d]{1,8})[\s\S]*?<!--'))

			new_log = Log()
			new_log.topic = self
			new_log.views = self.views
			if Log.objects.filter(topic=self):
				old_views = Log.objects.filter(topic=self).order_by('-datetime')[0]
				new_log.views_diff = self.views - old_views.views
			else:
				new_log.views_diff = 0
			new_log.save()

			# Выходим
			g.go(url='http://diesel.elcat.kg/index.php?act=Login&CODE=03')

			self.count += 1
			self.save()
			return True
		except:
			return False

	class Meta:
		ordering = ['-last_up']
		verbose_name = u'Топики'
		verbose_name_plural = u'Топики'

apps/diesel/forms.py
# -*- coding: utf-8 -*
import re
from grab import Grab

from django.conf import settings

from django import forms
from django.utils.translation import ugettext as _

from .models import Topic


class TopicForm(forms.ModelForm):
	password = forms.CharField(label=u'Пароль', widget=forms.PasswordInput(), help_text=u'на diesel.elcat.kg')

	class Meta:
		model = Topic
		fields = ['url', 'login', 'password']

	def clean_url(self):
		url = self.cleaned_data['url']
		url_regex = 'https?:\/\/diesel.elcat.kg\/index.php\?showtopic=([\d]+).*'
		compiled_url_regex = re.compile(url_regex)
		urls = compiled_url_regex.findall(url)
		if urls:
			real_url = 'http://diesel.elcat.kg/index.php?showtopic=' + urls[0]
			g = Grab()
			g.setup(
				connect_timeout=30,
				timeout=60
			)

			try:
				g.go(url=real_url)
			except:
				raise forms.ValidationError(u'Что то пошло не так.')

			html = g.response.body
			mes_regex = '<div class="([\w]+)" id=\\\'([\w]+)-([\d]+)\\\'>'
			compiled_mes_regex = re.compile(mes_regex)
			topics = compiled_mes_regex.findall(html)
			if not topics:
				raise forms.ValidationError(u'Топик не существует или удален.')

			return real_url
		else:
			raise forms.ValidationError(u'Не коректный url!')

	def clean(self):
		cleaned_data = super(TopicForm, self).clean()
		if 'login' not in cleaned_data:
			return cleaned_data
		login = cleaned_data['login'].encode('cp1251')
		if 'password' not in cleaned_data:
			return cleaned_data
		password = cleaned_data['password'].encode('cp1251')
		g = Grab()
		data = {
			'UserName': login,
			'PassWord': password,
		}
		g.setup(
			post=data,
			connect_timeout=30,
			timeout=60
		)

		try:
			g.go('http://diesel.elcat.kg/index.php?act=Login&CODE=01&CookieDate=1')
		except:
			raise forms.ValidationError(_('Something went wrong, please try again later.'))
		html = g.response.body
		ent_regex = 'function moz_redirect'
		compiled_ent_regex = re.compile(ent_regex)
		entry = compiled_ent_regex.findall(html)
		if not entry:
			raise forms.ValidationError(_('Invalid login or password.'))
		url = cleaned_data['url']
		try:
			g.go(url=url)
		except:
			raise forms.ValidationError(_('Something went wrong, please try again later.'))

		html = g.response.body
		log_regex = '<a href="javascript:;" title=".*?"><b>(.+?)</b></a>'
		compiled_log_regex = re.compile(log_regex)
		topic_login = compiled_log_regex.findall(html)[0]
		if topic_login.lower() != login.lower():
			raise forms.ValidationError(_('You can not UP someone else\'s topic! Topic Starter <b>') + topic_login.decode('cp1251') + _('</b>, you logged in as <b>') + login.decode('cp1251') + ('</b>.'))
		return cleaned_data

apps/diesel/views.py
# -*- coding: utf-8 -*
import datetime
from random import randint
from grab import Grab
from django.shortcuts import render
from django.shortcuts import redirect

from django.http import JsonResponse, HttpResponse

from django.contrib.auth.decorators import login_required

# from django.db.models import Count
from django.db.models import Sum
from django.db.models import Avg

from .forms import TopicForm

from .models import Topic
from .models import Log


@login_required
def topics(request):
	context = {}
	context['title'] = u'Темы'
	context['now'] = datetime.datetime.now()
	context['topics_active'] = Topic.objects.filter(user=request.user.id, public=True, deleted=False)

	return render(request, 'diesel_up/topics.html', context)


def up_force(request, id):
	topic = Topic.objects.get(id=id, deleted=False)
	print topic
	topic.up()
	return HttpResponse('ok')


@login_required
def add(request):
	context = {}
	context['title'] = u'Добавить тему'
	context['form'] = TopicForm(request.POST or None)

	if request.POST and context['form'].is_valid():
		new_topic = context['form'].save()
		new_topic.user = request.user
		new_topic.save()
		new_topic.up()
		print new_topic
		return redirect(topics)
	else:
		return render(request, 'diesel_up/add_topic.html', context)


@login_required
def edit(request, id):
	context = {}
	context['title'] = u'Edit'
	instance = Topic.objects.get(id=id, deleted=False)
	form = TopicForm(request.POST or None, instance=instance)

	if form.is_valid():
		form.save()
		return redirect(topics)

	context['form'] = form
	return render(request, 'diesel_up/edit_topic.html', context)


@login_required
def deleted(request, id):
	Topic.objects.get(id=id, user=request.user).delete()
	return HttpResponse('ok')

apps/diesel/templates/diesel_up/add_topic.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1 class="text-center title_form">Создать тему</h1>

<form method="post" class="form-horizontal col-md-5 col-md-offset-4" action='' onsubmit="yaCounter30149614.reachGoal('add'); return true;">
	{% csrf_token %}
    {{ form.errors }}
  <div class="form-group">
    <div class="col-sm-10">
      <input type="url" name="{{ form.url.name }}" class="form-control" id="id_url" placeholder="Url на diesel.elcat.kg">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <input type="text" name="{{ form.login.name }}" class="form-control" id="id_login" placeholder="Логин на diesel.elcat.kg">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <input type="password" name="{{ form.password.name }}" class="form-control" id="id_password" placeholder="Пароль на diesel.elcat.kg">
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-10">
      <button type="submit" class="btn btn-success col-md-6">Создать</button>
    </div>
  </div>

</form>

{% endblock %}

apps/diesel/templates/diesel_up/edit_topic.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1 class="text-center title_form">Создать тему</h1>

<form method="post" class="form-horizontal col-md-5 col-md-offset-4" action='' onsubmit="yaCounter30149614.reachGoal('add'); return true;">
	{% csrf_token %}
    {{ form.errors }}
  <div class="form-group">
    <div class="col-sm-10">
      <input type="url" name="{{ form.url.name }}" class="form-control" id="id_url" placeholder="Url на diesel.elcat.kg" value="{{ form.url.value }}">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <input type="text" name="{{ form.login.name }}" class="form-control" id="id_login" placeholder="Логин на diesel.elcat.kg" value="{{ form.login.value }}">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <input type="password" name="{{ form.password.name }}" class="form-control" id="id_password" placeholder="Пароль на diesel.elcat.kg">
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-10">
      <button type="submit" class="btn btn-success col-md-6">Создать</button>
    </div>
  </div>

</form>

{% endblock %}

apps/diesel/templates/diesel_up/facebook.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Ошибка доступа <span>(403)</span></h1>
  <p>Ошибка проверки CSRF. Запрос отклонён.</p>


  <p>Вы видите это сообщение, потому что данный сайт требует, чтобы при отправке форм была отправлена и CSRF-cookie. Данный тип cookie необходим по соображениям безопасности, чтобы убедиться, что ваш браузер не был взломан и не выполняет от вашего лица действий, запрограммированных третьими лицами.</p>
  <p>Если вы настроили свой браузер таким образом, чтобы он не передавал или не хранил cookie, пожалуйста, включите эту функцию вновь, по крайней мере для этого сайта, или для запросов, чьи домен и порт совпадают с доменом и портом текущей страницы.</p>

</div>

<div id="info">
  <h2>Help</h2>
    
    <p>Reason given for failure:</p>
    <pre>
    CSRF cookie not set.
    </pre>
    

  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
  <a
  href="https://docs.djangoproject.com/en/1.8/ref/csrf/">Django's
  CSRF mechanism</a> has not been used correctly.  For POST forms, you need to
  ensure:</p>

  <ul>
    <li>Your browser is accepting cookies.</li>

    <li>The view function passes a <code>request</code> to the template's <a
    href="https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render"><code>render</code></a>
    method.</li>

    <li>In the template, there is a <code>{% csrf_token
    %}</code> template tag inside each POST form that
    targets an internal URL.</li>

    <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use
    <code>csrf_protect</code> on any views that use the <code>csrf_token</code>
    template tag, as well as those that accept the POST data.</li>

  </ul>

  <p>You're seeing the help section of this page because you have <code>DEBUG =
  True</code> in your Django settings file. Change that to <code>False</code>,
  and only the initial error message will be displayed.  </p>

  <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>
</div>

</body>
</html>

apps/diesel/templates/diesel_up/log.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}

<h1>{{ topic.title }}</h1>

<p>{% trans "User" %} : {{ topic.login }}</p>
<p>{% trans "Topic" %} : <a href='{{ topic.url }}' target="_blank">{{ topic.title }}</a></p>
<p>{% trans "Views" %} : {{ topic.views }}</p>
<p>{% trans "Number up" %} : {{ topic.count }}</p>
<p>{% trans "Last up" %} : 
	<time 
		datetime='{{ topic.last_up|date:'Y.m.d H:i' }}'
		title='{{ topic.last_up|date:'Y.m.d H:i' }}'
	>
		{% if topic.last_up.year == now.year %}
			{{ topic.last_up|naturalday|title }} {{ topic.last_up|time:'H:i' }}
		{% else %}
			{{ topic.last_up|naturalday:"d E Y" }}
		{% endif %}
	</time>
</p>
<p>{% trans "Created at" %} :
	<time 
		datetime='{{ topic.created_at|date:'Y.m.d H:i' }}'
		title='{{ topic.created_at|date:'Y.m.d H:i' }}'
	>
		{% if topic.created_at.year == now.year %}
			{{ topic.created_at|naturalday:"d E" }} {{ topic.created_at|time:'G:i' }}
		{% else %}
			{{ topic.created_at|naturalday:"d E Y" }}
		{% endif %}
	</time>
</p>

<h2 class="b-log_title">{% trans "Statistics views" %}</h2>
<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
	<li class="active"><a href="#hour_st" data-toggle="tab">По часам</a></li>
	<li><a href="#day_st" data-toggle="tab">По дням</a></li>
	<li><a href="#week_st" data-toggle="tab">По неделям</a></li>
	<li><a href="#month_st" data-toggle="tab">По месяцам</a></li>
</ul>
<div id="my-tab-content" class="tab-content">
	<div class="tab-pane active" id="hour_st">
		<div id="hour_st_chart" class="fat"></div>
	</div>
	<div class="tab-pane" id="day_st">
		<div id="day_st_chart"></div>
	</div>
	<div class="tab-pane" id="week_st">
		<div id="week_st_chart"></div>
	</div>
	<div class="tab-pane" id="month_st">
		<div id="month_st_chart"></div>
	</div>
</div>


<h2 class="b-log_title">{% trans "Dynamics views" %}</h2>
<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
	<li class="active"><a href="#hour" data-toggle="tab">По часам</a></li>
	<li><a href="#day" data-toggle="tab">По дням</a></li>
	<li><a href="#week" data-toggle="tab">По неделям</a></li>
	<li><a href="#month" data-toggle="tab">По месяцам</a></li>
</ul>
<div id="my-tab-content" class="tab-content">
	<div class="tab-pane active" id="hour">
		<div id="hour_chart"></div>
	</div>
	<div class="tab-pane" id="day">
		<div id="day_chart"></div>
	</div>
	<div class="tab-pane" id="week">
		<div id="week_chart"></div>
	</div>
	<div class="tab-pane" id="month">
		<div id="month_chart"></div>
	</div>
</div>


<!-- Statistics hour -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Статистика просмотров'],
				{% for log in hour_views %}
					['{{ log.hour }}', {{ log.preHour|floatformat:'-0' }}],
				{% endfor %}
			]);
		var options = {
			curveType: 'function',
			legend: 'none',
			colors: ['blue'],
			width: 1216,
			height: 500,
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('hour_st_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Statistics day_views -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Статистика просмотров'],
			{% for log in day_views %}
				['{{ log.day }}', {{ log.preDay|floatformat:'-0' }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			width: 1216,
			height: 500,
			legend: 'none',
			colors: ['blue'],
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('day_st_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Statistics week_views -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Статистика просмотров'],
			{% for log in week_views %}
				['{{ log.week }}', {{ log.preWeek|floatformat:'-0' }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			width: 1216,
			height: 500,
			legend: 'none',
			colors: ['blue'],
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('week_st_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Statistics month_views -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Статистика просмотров'],
			{% for log in month_views %}
				['{{ log.month }}', {{ log.preMonth|floatformat:'-0' }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			legend: 'none',
			colors: ['blue'],
			width: 1216,
			height: 500,
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('month_st_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Chart hour -->


<!-- Dynamics hour -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Разница просмотров'],
			{% for log in hour %}
				['{{ log.hour }}', {{ log.perHour }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			legend: 'none',
			width: 1216,
			height: 500,
			colors: ['green'],
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('hour_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Dynamics day -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Разница просмотров'],
			{% for log in day %}
				['{{ log.day }}', {{ log.perDay }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			width: 1216,
			height: 500,
			legend: 'none',
			colors: ['green'],
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('day_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Dynamics week -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Разница просмотров'],
			{% for log in week %}
				['{{ log.week }}', {{ log.perWeek }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			legend: 'none',
			colors: ['green'],
			width: 1216,
			height: 500,
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('week_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Dynamics month -->
<script type="text/javascript"
	src="https://www.google.com/jsapi?autoload={
		'modules':[{
		'name':'visualization',
		'version':'1',
		'packages':['corechart']
		}]
	}">
</script>

<script type="text/javascript">
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Время', 'Разница просмотров'],
			{% for log in month %}
				['{{ log.month }}', {{ log.perMonth }}],
			{% endfor %}
		]);
		var options = {
			curveType: 'function',
			legend: 'none',
			colors: ['green'],
			width: 1216,
			height: 500,
			chartArea: {left:80,top:30,width:'100%',height:'80%'}
		};
		var chart = new google.visualization.LineChart(document.getElementById('month_chart'));
		chart.draw(data, options);
	}
</script>
<!-- Dynamics chart -->


<script type="text/javascript">
	jQuery(document).ready(function ($) {
		$('#tabs').tab();
	});
</script>


<script>
if ($('{% for log in hour %} ['{{ log.hour }}', {{ log.perHour }}], {% endfor %}').length == 0) {
	$('.b-log_title, .nav-tabs, .tab-pane').hide();
	document.write("<h2>Нет данных о статистике просмотров!</h2>");
}
</script>
{% endblock %}

apps/diesel/templates/diesel_up/up.html
up.html