apps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',

    url(r'^', include('apps.accounts.urls')),
	# Admin
	url(r'^admin/', include(admin.site.urls)),

	# Home
	url(r'^$', 'apps.views.home', name='home'),
	url(r'^results/$', 'apps.views.todos', name='todos'),
	url(r'^(?P<id>\d+)/$', 'apps.views.del_todo', name='del_todo'),
	url(r'^done/(?P<id>\d+)/$', 'apps.views.done_todo', name='done_todo'),

	url(r'^diesel-up/', include('apps.diesel.urls')),

	url(r'^chat/', include('apps.chat.urls')),

	url(r'^finance/', include('apps.finance.urls')),
)


# For serve static, media, templates in develop mode
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

apps/todo/models.py
# coding: utf-8
from django.db import models


class Todo(models.Model):
	title = models.CharField(verbose_name=u'Заголовок', max_length=256)
	text = models.TextField(verbose_name=u'Текст')
	created = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
	personal = models.BooleanField(verbose_name=u'Персональная задача', default=False)
	work = models.BooleanField(verbose_name=u'Рабочая задача', default=False)
	is_done = models.BooleanField(verbose_name=u'Выполнено', default=False)

	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ['created']
		verbose_name = u'Задача'
		verbose_name_plural = u'Задачи'

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% include "head.html" %}
</head>
<body>
<header>
    {% include "header.html" %}

</header>
{% block content %}{% endblock %}
<footer class="b-footer">
    {% include "footer.html" %}
</footer>
</body>
</html>

templates/head.html
<meta charset="UTF-8">
<title>{{ title }}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/templates/styles/style.css">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,500,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>



templates/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Any-do</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Ежедневник</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Diesel-up <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'diesel_up_topics' %}">Все темы</a></li>
                        <li><a href="{% url 'diesel_up_add' %}">Добавить тему</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'chat_form' %}">Чат</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Кошелек <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a href="{% url 'category' category.id %}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>

            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#">{{ user }}</a></li>
                    <li><a href="{% url 'logout' %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/main.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Добавить задачу</h1>
    <form method="post" class="form-horizontal col-md-5 col-md-offset-4">
        {% csrf_token %}
        <div class="form-group  {% if form.title.errors %}has-error{% endif %}">
            <div class="col-sm-10">
                {% if form.title.errors %}
                    <p>Обязательное поле</p>
                {% endif %}
                <input type="text" name="{{ form.title.name }}"
                       id="id_title {% if form.title.errors %}inputError2{% endif %}"
                       class="form-control col-md-12" placeholder="Заголовок задачи"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <div class="checkbox">
                    <label class="checkbox-inline">
                        <input type="checkbox" id="id_personal" name="{{ form.personal.name }}"> Персональная
                        задача
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" id="id_work" name="{{ form.work.name }}"> Рабочая задача
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-default button">Создать задачу</button>
            </div>
        </div>
    </form>

    <ul class="nav nav-pills col-md-5 col-md-offset-4 filter_todo">
        <li class="all_search">Все задачи</li>
        <li class="personal_search">Персональные задачи</li>
        <li class="work_search">Рабочие задачи</li>
        <input type="hidden" name="personal" value="True" class="personal">
        <input type="hidden" name="work" value="True" class="work">
    </ul>
    <div class="result_todo col-md-12"></div>
    <script>
        $('.personal_search').on('click', function (e) {
            e.preventDefault();
            $('.personal').prop('checked', true);
            $('.work').prop('checked', false);
            $.get('/results/' + '?personal=True', function (response) {
                $('.result_todo').html(response);
            });
        });

        $('.work_search').on('click', function (e) {
            e.preventDefault();
            $('.work').prop('checked', true);
            $('.personal').prop('checked', false);
            $.get('/results/' + '?work=True', function (response) {
                $('.result_todo').html(response);
            });
        });

        $('.all_search').on('click', function (e) {
            e.preventDefault();
            $('.work').prop('checked', false);
            $('.personal').prop('checked', false);
            $.get('/results/', function (response) {
                $('.result_todo').html(response);
            });
        });

    </script>
{% endblock %}

templates/results.html
<table class="table table-bordered">
    <thead>
    <tr>
        <th>#</th>
        <th>Задача</th>
        <th>Дата оздания</th>
        <th>Статус</th>
        <th colspan="2" class="text-center">Опции</th>
    </tr>
    </thead>
    <tbody>
    {% for todo in todos %}
        <tr class="todo_active">
            <th scope="row">{{ todo.id }}</th>
            <td>{{ todo.title }}</td>
            <td>{{ todo.created|date:'d-m-Y H:i' }}</td>
            <td class="status_todo">
                {% if todo.personal %}
                    Персональная задача
                {% elif todo.work %}
                    Рабочая задача
                {% else %}
                    Не выбран
                {% endif %}
            </td>
            <td class="text-center"><a href="{% url 'del_todo' todo.id %}" data-id="{{ todo.id }}"
                                       data-token="{{ csrf_token }}"
                                       class="del_todo">Удалить</a></td>
            <td class="text-center"><a href="{% url 'done_todo' todo.id %}" data-id="{{ todo.id }}"
                                       data-token="{{ csrf_token }}"
                                       class="done_todo">Выполнено</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<script>
    $('.del_todo').on('click', function (e) {
        e.preventDefault();
        del = $(this);
        $.ajax({
            type: "POST",
            url: del.attr('href'),
            data: {
                'csrfmiddlewaretoken': del.attr('data-token'),
                'data_id': del.attr('data-id')
            },
            success: function () {
                del.parent().parent().remove()
            }
        });
    });
</script>